# Application configuration
# 
# This file defines all configuration values for a mangoo I/O application.
# The default values are loaded by default and overwritten by environment specific
# values if they are configured.
#
# Possible environments are test and dev.
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

default:
    application:
        name       : foo
        secret     : myvoiceismysecretmyvoiceismysecret
        language   : en
    connector:
        http:
            host      : 127.0.0.1
            port      : 8080   
        minify:
            js        : false
            css       : false
            jsfolder  : /foo
            cssfolder : /bar
            gzipjs    : false
            gzipcss   : false
    auth:
        redirect  : /login
        cookie:
            name    : ${application-name}-AUTH
            encrypt : false
            expires : 86400
    cookie:
        name       : ${application-name}-SESSION
        expires    : 86400
        encryption : false
    smtp:
        host       : localhost
        port       : 25
        username   : 
        password   : 
        ssl        : false
        
test:
    connector:
        http:
            host      : 127.0.0.1
            port      : 10808 
    smtp:
        port       : 3055
        
dev:
    connector:
        http:
            host      : 127.0.0.1
            port      : 10808 
    smtp:
        port       : 3025